### ISSUE TITLE
Using Mapreduce program for the first time

### ISSUE THREAD

**Issue by Manthan-develper** [Manthan-develper/Hadoop#2]
Writing a mapreduce program can be a tough nut to crack however 
### There are some mapreduce programs that are already present in the mapreduce folder 
**C:\hadoop\share\hadoop\mapreduce**

`hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan`

**Error**

_

> Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
>         at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
>         at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
>         at java.nio.file.Files.createDirectory(Files.java:674)
>         at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
>         at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
>         at java.nio.file.Files.createTempDirectory(Files.java:950)
>         at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
>         at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

Finding the solution 
![image](https://github.com/user-attachments/assets/82311108-5672-402d-a59d-4800d44983ca)

**Comment by Manthan-develper** [comment]
Got this solution on Co pilot trying this soution
This error occurs because Windows does not support POSIX permissions, which are typically used in Unix-based systems. When you try to set POSIX permissions on a Windows file system, it results in this `UnsupportedOperationException`.

### Solution
To resolve this issue, you can modify the Hadoop configuration to disable POSIX permissions on Windows. Here's how you can do it:

1. **Edit `core-site.xml`:**
   - Open the `core-site.xml` file located in your Hadoop configuration directory (typically `/etc/hadoop/conf/` or `/usr/local/hadoop/etc/hadoop/`).
   - Add the following property to disable POSIX permissions:
     ```xml
     <property>
         <name>fs.permissions.umask-mode</name>
         <value>000</value>
     </property>
     ```
   - Save and close the file.

2. **Restart Hadoop Services:**
   - Restart the Hadoop services to apply the changes:
     ```sh
     start-dfs.cmd
     start-yarn.cmd
     ```

### Explanation
Setting `fs.permissions.umask-mode` to `000` disables POSIX permissions, allowing Hadoop to run on Windows without encountering the `UnsupportedOperationException`.

By following these steps, you should be able to resolve the issue. If you have any further questions or need additional assistance, feel free to ask!

**Comment by Manthan-develper** [comment]
These are the commands used today

`C:\WINDOWS\System32>cd C:\hadoop\sbin

C:\hadoop\sbin>start-all.cmd
This script is Deprecated. Instead use start-dfs.cmd and start-yarn.cmd
starting yarn daemons

C:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

C:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\newtemp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

C:\hadoop\sbin>icacls C:\hadoop\temp /grant %username%:F
processed file: C:\hadoop\temp
Successfully processed 1 files; Failed processing 0 files

C:\hadoop\sbin>set HADOOP_TMP_DIR=C:\hadoop\newtemp

C:\hadoop\sbin>set HADOOP_TMP_DIR=C:\hadoop\newtemp

C:\hadoop\sbin>mkdir C:\hadoop\newtemp

C:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\newtemp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

C:\hadoop\sbin>set HADOOP_TMP_DIR=C:\hadoop\newtemp

C:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\newtemp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

C:\hadoop\sbin>set JAVA_HOME=C:\Program Files\Java\jdk-<version>
The syntax of the command is incorrect.

C:\hadoop\sbin>set HADOOP_HOME=C:\hadoop

C:\hadoop\sbin>set HADOOP_CONF_DIR=%HADOOP_HOME%\etc\hadoop

C:\hadoop\sbin>set HADOOP_OPTS=-Djava.io.tmpdir=C:\hadoop\temp

C:\hadoop\sbin>java -version
java version "1.8.0_431"
Java(TM) SE Runtime Environment (build 1.8.0_431-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.431-b10, mixed mode)

C:\hadoop\sbin>stop-all.cmd
This script is Deprecated. Instead use stop-dfs.cmd and stop-yarn.cmd
SUCCESS: Sent termination signal to the process with PID 14204.
SUCCESS: Sent termination signal to the process with PID 6356.
stopping yarn daemons
SUCCESS: Sent termination signal to the process with PID 9896.
SUCCESS: Sent termination signal to the process with PID 17780.

INFO: No tasks running with the specified criteria.

C:\hadoop\sbin>start-all.cmd
This script is Deprecated. Instead use start-dfs.cmd and start-yarn.cmd
starting yarn daemons

C:\hadoop\sbin>hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:496)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:950)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:296)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:245)

C:\hadoop\sbin>`

**Comment by Manthan-develper** [comment]
![image](https://github.com/user-attachments/assets/fa2ccc8c-7c9f-44a7-8861-09347de73a83)

**Comment by Manthan-develper** [comment]
Understood. Let's try a few more steps to resolve this issue. It's possible there might be underlying issues we haven't addressed yet. Here are some additional steps we can take:

### Step-by-Step Advanced Troubleshooting

1. **Ensure No Path Conflicts**
   - Verify that there are no conflicts in the environment variables. Check for any other Hadoop installations or conflicting paths.
   ```sh
   echo %PATH%
   echo %JAVA_HOME%
   echo %HADOOP_HOME%
   ```

2. **Verify Java Version Compatibility**
   - Ensure that the Java version you're using is compatible with Hadoop. Sometimes, newer or older versions of Java might cause issues.
   ```sh
   java -version
   ```

3. **Check for Other Running Instances**
   - Make sure there are no other instances of Hadoop services running that might be causing conflicts.
   ```sh
   jps
   ```

4. **Use Alternative Temp Directory**
   - Try setting a different temporary directory directly in the command line to see if that helps.
   ```sh
   hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\alternativeTemp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
   ```

5. **Check Hadoop Directory Structure**
   - Ensure that the Hadoop directory structure is intact and all necessary files are in place. Sometimes, issues can arise if files are missing or corrupted.

6. **Run Hadoop in Debug Mode**
   - Running Hadoop in debug mode can provide more detailed information about what is going wrong. This can help identify the root cause of the problem.
   ```sh
   hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\temp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan -D mapreduce.job.user.classpath.first=true
   ```

7. **Review System Logs**
   - Check the Windows Event Viewer for any system logs that might provide additional insights.
   ```sh
   eventvwr
   ```

8. **Reinstall Hadoop**
   - As a last resort, consider reinstalling Hadoop. This can resolve any underlying installation issues that might be causing the problem.
   ```sh
   rmdir /S /Q C:\hadoop
   mkdir C:\hadoop
   tar -xzf hadoop-x.y.z.tar.gz -C C:\hadoop
   ```

By following these advanced troubleshooting steps, we can try to isolate and resolve the issue. If you still encounter problems, please share any additional error messages or logs, and we can continue to debug further. I'm here to help!

**Comment by Manthan-develper** [comment]
I understand that the problem is persisting despite trying the suggested solutions. Let's take another approach to troubleshoot and resolve this issue:

### Complete Fresh Installation of Hadoop

1. **Uninstall Current Hadoop Setup:**
   - Ensure all Hadoop services are stopped.
   - Remove the current Hadoop installation and all related directories.

   ```sh
   stop-dfs.cmd
   stop-yarn.cmd
   rmdir /S /Q C:\hadoop
   ```

2. **Reinstall Hadoop:**
   - Download the latest version of Hadoop from the [Apache Hadoop website](https://hadoop.apache.org/releases.html).
   - Extract the downloaded file to `C:\hadoop`.

   ```sh
   tar -xzf hadoop-x.y.z.tar.gz -C C:\hadoop
   ```

3. **Set Environment Variables:**
   - Ensure the environment variables for Java and Hadoop are set correctly.

   ```sh
   setx JAVA_HOME "C:\Program Files\Java\jdk-<version>"
   setx HADOOP_HOME "C:\hadoop"
   setx PATH "%PATH%;%HADOOP_HOME%\bin;%JAVA_HOME%\bin"
   setx HADOOP_CONF_DIR "%HADOOP_HOME%\etc\hadoop"
   ```

4. **Configure Hadoop:**
   - Edit the configuration files (`core-site.xml`, `hdfs-site.xml`, `mapred-site.xml`, and `yarn-site.xml`) in the `C:\hadoop\etc\hadoop` directory.
   - Add the property to disable POSIX permission checks in `core-site.xml`.

   ```xml
   <property>
       <name>fs.permissions.umask-mode</name>
       <value>000</value>
   </property>
   ```

5. **Format the NameNode:**
   - Format the NameNode before starting the services.

   ```sh
   hdfs namenode -format
   ```

6. **Start Hadoop Services:**
   - Start the Hadoop services using the provided script files.

   ```sh
   start-dfs.cmd
   start-yarn.cmd
   ```

7. **Run Your Hadoop Job:**
   - Now, try running your Hadoop job with the `-Djava.io.tmpdir` option to specify the temporary directory.

   ```sh
   hadoop jar C:\hadoop\share\hadoop\mapreduce\hadoop-mapreduce-examples-3.4.0.jar wordcount -Djava.io.tmpdir=C:\hadoop\temp C:\Users\manth\Downloads\archive\Manthan.txt /output/test_Manthan
   ```

### Additional Checks

1. **Check Java Version Compatibility:**
   - Ensure the Java version you are using is compatible with the version of Hadoop you are installing.

2. **Ensure Correct File System:**
   - Confirm that the file system where Hadoop is installed and running is NTFS, as some operations may not be compatible with FAT32 or other file systems.

By carefully following these steps, you should be able to set up a fresh Hadoop environment and avoid the `UnsupportedOperationException`. If the issue still persists, please provide any new error messages or details, and I'll assist you further!
